// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCallIssueRedirects } from './src/domain/calls/callRoutes';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Pending PR-only EIPs are external PR records, not canonical Forkcast pages.
// `/eips/{pendingId}` redirects to the GitHub PR so previously-shared URLs keep
// resolving. Computed from the compiled eips.json (run `compile-eips` first).
function pendingEipRedirects() {
  try {
    const eips = JSON.parse(
      fs.readFileSync(path.join(__dirname, 'src/data/eips.json'), 'utf-8'),
    );
    /** @type {Record<string, string>} */
    const out = {};
    for (const eip of eips) {
      if (eip?.pendingPullRequest?.url) {
        out[`/eips/${eip.id}`] = eip.pendingPullRequest.url;
      }
    }
    return out;
  } catch {
    // eips.json is generated by `compile-eips`; if it's missing (e.g. a bare
    // editor check), skip the pending redirects rather than failing config load.
    return {};
  }
}

// Legacy `/calls/{githubIssue}` aliases -> canonical `/calls/{series}/{number}`,
// derived from the compiled call data (run a call sync first). Replaces the SPA's
// in-React issue-number redirect. Derivation + invariant test live in
// src/domain/calls/callRoutes.ts.
function callIssueRedirects() {
  try {
    const calls = JSON.parse(
      fs.readFileSync(path.join(__dirname, 'src/data/protocol-calls.generated.json'), 'utf-8'),
    );
    return buildCallIssueRedirects(calls);
  } catch {
    // Skip rather than fail config load if the compiled call data is missing.
    return {};
  }
}

// Simple legacy aliases. Static builds emit these as `<meta http-equiv="refresh">`
// pages (Phase 1 does not require HTTP 301/302). See intentional-feature-removals.md.
const legacyRedirects = {
  '/feedback':
    'https://ethereum-magicians.org/t/community-feedback-on-non-headlining-features-in-glamsterdam/26410',
  '/planner': '/schedule',
  '/glamsterdam': '/upgrade/glamsterdam',
  '/glamsterdam/priority': '/upgrade/glamsterdam/client-priority',
  '/glamsterdam/complexity': '/upgrade/glamsterdam/test-complexity',
  '/priority': '/upgrade/glamsterdam/client-priority',
  '/complexity': '/upgrade/glamsterdam/test-complexity',
  '/upgrade/glamsterdam/candidates': '/upgrade/glamsterdam/devnet-inclusion',
  '/upgrade/glamsterdam/priority': '/upgrade/glamsterdam/client-priority',
  '/upgrade/glamsterdam/complexity': '/upgrade/glamsterdam/test-complexity',
  '/upgrade/glamsterdam/devnets': '/upgrade/glamsterdam/devnet-inclusion',
  '/upgrade/glamsterdam/devnets/priority': '/upgrade/glamsterdam/client-priority',
  '/upgrade/glamsterdam/devnets/complexity': '/upgrade/glamsterdam/test-complexity',
};

// https://astro.build/config
export default defineConfig({
  site: 'https://forkcast.org',
  output: 'static',
  integrations: [react(), sitemap()],
  vite: {
    plugins: [tailwindcss()],
  },
  redirects: {
    ...legacyRedirects,
    ...pendingEipRedirects(),
    ...callIssueRedirects(),
  },
});
